# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c91ce675dbaf14054d9316ef1c01cee9b379dd2f29f18f25a8d979f3108ac3aa1d56ce70e54e82c635949fb1a6914b420d5535f6058fcc5ae514a3865a60c8f

test:
  secret_key_base: a8cfdbf3a5b50f30a2a6d4d1be28dbb05f26997330107126833dca1b6fa53b4823489850ae83df817c9f9bc61956398af0efd9a9958c7eb4e19467f98c2cfed4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
